name: Build and test R

on: [push, pull_request]

jobs:
  R-make-test:
    runs-on: ubuntu-latest
    
    - uses: actions/checkout@master

    - name: Configure R
      run: |
        cd r-devel
        ./configure

    - name: Build R
      run: |
        cd r-devel
        make

    - name: Test R
      run: |
        cd r-devel
        make check-devel
