name: Build and test R

on: [push, pull_request]

jobs:
  R-make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: System setup
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran g++ \
            libreadline8 libreadline-dev xorg-dev libbz2-dev \
            liblzma-dev libpcre2-deva libcurl4-openssl-dev \
            libjpeg-dev libcairo2-dev libtiff-dev libicu-dev

      - name: Configure R
        run: |
          cd r-devel
          ./configure --without-recommended-packages

      - name: Build R
        run: |
          cd r-devel
          make

      - name: Test R
        run: |
          cd r-devel
          make check-devel
