name: Build and test R

on: [push, pull_request]

jobs:
  R-make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: System setup
        #TODO: cache this step uses: actions/cache@v2
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion gfortran g++ \
            libreadline-dev xorg-dev libbz2-dev \
            liblzma-dev libpcre2-dev libcurl4-openssl-dev \
            libjpeg-dev libcairo2-dev libtiff-dev libicu-dev \
            texinfo texlive

      - name: Configure R
        run: |
          cd r-devel
          ./tools/rsync-recommended
          ./configure

      - name: Build R
        run: |
          cd r-devel
          make

      - name: Test R
        run: |
          cd r-devel
          make check-devel

      - name: Create patch
        uses: actions/upload-artifact@v2
        with:
          name: patch
          path: r-devel/patch
        run: |
          cd r-devel
          svn diff > patch
