name: Update SVN snapshot

on:
  schedule:
    # daily, 4 AM UTC
    - cron:  '0 4 * * *'

jobs:
  svn-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install subversion
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion
      - name: Update SVN copy
        run: |
          cd r-devel
          svn update
